---
# file: project/ansible-role-oracle-express.yml

- hosts: ansible-role-oracle-express
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/ansible-role-oracle-express"
    - debug: var=fact_role_path

  roles:

    - ansible-role-oracle-express
