---
# file: project/oracle_express_role.yml

- hosts: oracle_express_role
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name

    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/roles/oracle_express_role"
    - debug: var=fact_role_path

  roles:

    - ansible-role-oracle-express
